name: C/C++ CI



on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt 
      uses: jurplel/install-qt-action@v2
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: qmake
      run: qmake
    - name: make
      run: make
    - name: exists
      run: file UltimateTexasHoldem
